class MultiattributeTestClass < ActiveRecord::Base
  include UniqueAttributes
  unique_attribute :autogenerated_username, proc { generate_username }
  unique_attribute :autogenerated_password, proc { generate_password }

  def self.generate_username
    SecureRandom.hex
  end

  def self.generate_password
    SecureRandom.hex
  end
end
