# frozen_string_literal: true

class ScopedTestClass < ApplicationRecord
  include UniqueAttributes
  unique_attribute :autogenerated_username,
                   proc { generate_username },
                   scope: :other_field

  def self.generate_username
    SecureRandom.hex
  end
end
