# frozen_string_literal: true

class TestClass < ApplicationRecord
  include UniqueAttributes
  unique_attribute :autogenerated_username, (proc { generate_username })

  def self.generate_username
    SecureRandom.hex
  end
end
