# based on https://github.com/ruby/setup-ruby/blob/master/README.md
name: Tests
on: [push, pull_request]
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ 2.7, 3.1, 3.2 ]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: unique_attributes_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      CI: true
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo apt-get install libsqlite3-dev
    - run: bundle exec rspec
    - run: bundle exec rubocop
      if: matrix.ruby == 3.2
